import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import EntryList from "@/components/entryList";
import EntryCard from "@/components/entryCard";
import useSWR from "swr";

export default function Home() {
  const { data } = useSWR("/lib/db.json");
  console.log(data);
  if (!data) {
    return <h1>Loading...</h1>;
  }
  if (data) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <EntryList>
            <EntryCard />
          </EntryList>
        </main>
      </>
    );
  }
}
