import Head from "next/head";
import EntryList from "@/components/entryList";
import EntryCard from "@/components/entryCard";
import db from "../lib/db.json";
import { useState } from "react";
import Header from "@/components/Header";

export default function Home() {
  const [poi, setPoi] = useState(db);

  if (poi)
    return (
      <>
        <Head>
          <title>Tourio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <EntryList>
            {poi.map(({ id, image, name, location }) => {
              return (
                <EntryCard
                  key={id}
                  image={image}
                  name={name}
                  location={location}
                />
              );
            })}
          </EntryList>
        </main>
      </>
    );
}
