import Head from "next/head";
import EntryList from "@/components/entryList";
import EntryCard from "@/components/entryCard";
import db from "../lib/db.json";
import { useState } from "react";
import Header from "@/components/Header";
import Link from "next/link";
import useSWR from "swr";

export default function Home() {
  const [poi, setPoi] = useState(db);
  const { data, isLoading, error } = useSWR("/api/locations");

  if (error) return <div>failed to load</div>;

  if (isLoading) return <div>loading...</div>;

  if (data)
    return (
      <>
        <Head>
          <title>Tourio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <Link href="/AddPlace">Add Place +</Link>
          <EntryList>
            {data.map(({ _id, image, name, location }) => {
              return (
                <EntryCard
                  key={_id}
                  image={image}
                  name={name}
                  location={location}
                />
              );
            })}
          </EntryList>
        </main>
      </>
    );
}
